# Generated by Django 5.0 on 2023-12-15 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='standard',
            field=models.CharField(choices=[('2009', '2009'), ('2018', '2018'), ('2020', '2020')], default=datetime.datetime(2023, 12, 15, 16, 2, 48, 123243, tzinfo=datetime.timezone.utc), max_length=4),
            preserve_default=False,
        ),
    ]
